# general parameters
file_path: 'envs/Reacher_Linux_Single_NoVis/Reacher.x86_64'
#file_path: 'envs/Reacher_Single.app'
model_file: 'models/first_ddpg.pkl'
graph_file: 'training-performance.png'

###########################################################################
# valid values include 'random', 'ddpg'
alg: 'ddpg'
###########################################################################

# parameters for printing and controlling learning time
frame_time: 0.00
max_episodes: 500
max_iterations: 10000

# model parameters
model_params:
  # training parameters
  gamma: 0.99
  alpha: 0.01
  t_freq: 100
  tau: 0.001

  # epsilon decay for random noise
  epsilon: 1.0
  epsilon_decay: [0.99999, 0.99995, 0.9999, 0.9995, 0.999]
  epsilon_min: 0.01

  # parameters for the replay buffer
  buffer_size: 1000000
  batch_size: 64

  # architecture
  inter_dims: [128, 256, 256, 512, 512]