# general parameters
file_path: 'envs/Reacher_Linux_Single_NoVis/Reacher.x86_64'
#file_path: 'envs/Reacher_Single.app'
model_file: 'models/first_ddpg.pkl'
graph_file: 'training-performance.png'

###########################################################################
# valid values include 'random', 'ddpg'
alg: 'ddpg'
###########################################################################

# parameters for printing and controlling learning time
frame_time: 0.00
max_episodes: 500
max_iterations: 10000
t_update: 10  # number of time steps to take before update
num_updates: 20  # number of network updates to complete in a time step

# model parameters
model_params:
  # training parameters
  gamma: 0.99
  actor_alpha: 0.0001
  critic_alpha: 0.001
  t_freq: 100
  tau: 0.0001

  # parameters for the Ornstein-Uhlenbeck noise process
  use_ornstein: True
  theta: 0.2
  sigma: 0.3
  mu: 0.0
  dt: 0.01
  # general noise (NOT applied if using Ornstein-Uhlenbeck)
  epsilon: 1.0
  epsilon_decay: 0.999999
  epsilon_min: 0.01
  noise_variance: 0.5

  # parameters for the replay buffer
  buffer_size: 1000000
  batch_size: 64

  # architecture
  inter_dims: [256, 256, 512, 512, 1024]
  use_batch_norm: True