# general parameters
#file_path: 'envs/Reacher_Linux_Single_NoVis/Reacher.x86_64'
file_path: 'envs/Reacher_Single.app'
model_file: 'models/first_ddpg.pkl'

###########################################################################
# valid values include 'random', 'ddpg'
alg: 'ddpg'
###########################################################################

# parameters for printing and controlling learning time
frame_time: 0.00
max_episodes: 2000
max_iterations: 10000

# model parameters
model_params:
  # training parameters
  epsilon: 1.0
  epsilon_decay: 0.996
  epsilon_min: 0.05
  gamma: 0.99
  alpha: 0.001
  t_freq: 100
  tau: 0.01

  # parameters for the replay buffer
  buffer_size: 1000000
  batch_size: 64

  # architecture
  inter_dims: [128, 256, 256, 512, 512]